import Head from "next/head";
import Layout from "@/components/Layout";
import AnimatedText from "@/components/AnimatedText";
import HireMe from "@/components/HireMe";
import TransitionEffect from "@/components/TransitionEffect";
import Link from "next/link";

export default function Home() {
    return (
        <>
            <Head>
                <title>Yi Qing Khoo</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <TransitionEffect />
            <main className="flex items-center text-dark w-full  dark:text-light"> {/*min-h-screen */}
                <Layout className="pt-0 md:pt-16 sm:pt-8">
                    <div className="flex items-center justify-between w-full lg:flex-col">
                        {/*<div className="w-1/2 md:w-full">
                            <Image
                                src={profilePic}
                                alt="YQ"
                                className="w-full h-auto lg:hidden md:inline-block md:w-full "
                                priority
                                sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 50vw"
                            />
                        </div>*/}
                        <div className="w-full flex flex-col items-center self-center lg:text-center">
                            <AnimatedText
                                text="Hi, I'm Yi Qing Khoo. "
                                className="!text-center !text-6xl xl:!text-5xl  lg:!text-6xl md:!text-5xl sm:!text-3xl"
                            />
                            <p className="my-4 text-base font-medium md:text-sm sm:text-xs text-center">
                                Explore my projects and works that showcases my skills in UI UX design, Visual design and programming.
                            </p>
                            <div className="flex flex-row gap-4">
                            <Link
                                    href="/projects"
                                    className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold 
                                    hover:bg-light hover:text-dark 
                                    border-2 border-solid border-transparent hover:border-dark
                                    dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light
                                    md:p-2 md:px-4 md:text-base 
                                    "
                                    download={true}>
                                    Projects
                            </Link>
                                                        <Link
                                    href="/work"
                                    className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold 
                                    hover:bg-light hover:text-dark 
                                    border-2 border-solid border-transparent hover:border-dark
                                    dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light
                                    md:p-2 md:px-4 md:text-base 
                                    "
                                    download={true}>
                                    Work
                                </Link>
                                </div>
 
                        </div>
                    </div>
                </Layout>
                <HireMe />
            </main>
        </>
    );
}
