import Head from "next/head";
import Layout from "@/components/Layout";
import AnimatedText from "@/components/AnimatedText";
import TransitionEffect from "@/components/TransitionEffect";
import Projects from "../components/Projects";

export default function Home() {
	return (
		<>
			<Head>
				<title>Yi Qing Khoo</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<TransitionEffect />
			<main className="flex items-center text-dark w-full  dark:text-light">
				{" "}
				{/*min-h-screen */}
				<Layout className="pt-0 md:pt-16 sm:pt-8">
					<div className="flex items-center justify-between w-full lg:flex-col">
						<div className="w-full flex flex-col items-center self-center lg:text-center">
							<AnimatedText
								text="Hi, I'm Yi Qing Khoo. "
								className="!text-center !text-6xl xl:!text-5xl  lg:!text-6xl md:!text-5xl sm:!text-3xl"
							/>
							<p className="text-center text-2xl pb-6 border-b-2 border-black dark:border-light">
								With an M.S. in Human-Computer Interaction and B.S. in Computer Science, I am looking to
								leverage my skills in the tech industry.
							</p>
							<p className="text-center text-xl mb-12 pt-2">
								View projects below where I showcase my ability in prototyping, designing and conducting
								mixed-method user research and testing.
							</p>

							{/*<h5 className=" mb-4 md:text-sm sm:text-xs text-center">
								Explore my projects and works that showcases my skills in
								<br />
								<span className="font-bold text-primary dark:text-primaryDark">
									UI UX design & research
								</span>
								,<span className="font-bold text-primary dark:text-primaryDark">Visual design</span> and
								<span className="font-bold text-primary dark:text-primaryDark"> Programming</span>.
	</h5>*/}
						</div>
					</div>
					<Projects />
				</Layout>
				{/*<HireMe />*/}
			</main>
		</>
	);
}
